package com.company.UI.EPKUI;

public enum Type_Of_Error {
    NOT_REACHABLE,
    NO_SUCCESSORS,
    MISSING_OR_WRONG_SETTINGS,
    EPK_RULE_MISSED_TOO_MANY_SUCESSORS,
    EPK_RULE_MISSED_WRONG_SUCESSORS,
    EPK_RULE_MISSED_GATE_SUCC_PRE_TYPE,
    ACTIVATING_MISSING_SISTERBLOCK,
    EPK_RULE_MISSED_TOO_FEW_SUCESSORS,
    EPK_RULE_MISSED_TOO_MANY_PREDECESSORS,
    EPK_RULE_MISSED_TOO_FEW_PREDECESSORS;
}
